// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-pH_glrq1MxYaxqzQbzXPjlfm7jawaUk',
    appId: '1:695550397936:web:e4f07f158f02c5bc28a135',
    messagingSenderId: '695550397936',
    projectId: 'recipeat-app',
    authDomain: 'recipeat-app.firebaseapp.com',
    storageBucket: 'recipeat-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyR_8WM-DWm9ZXs7jsQxQvzaohP_IK9uw',
    appId: '1:695550397936:android:c63016bc257457f628a135',
    messagingSenderId: '695550397936',
    projectId: 'recipeat-app',
    storageBucket: 'recipeat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoNQBUzWpppdbsQ8sDGEUn3QSxq595-M',
    appId: '1:695550397936:ios:72009be59cce711928a135',
    messagingSenderId: '695550397936',
    projectId: 'recipeat-app',
    storageBucket: 'recipeat-app.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );
}
